version: '3.8'

services:
  ocr_service:
    build:
      context: ./cmd/ocr_service
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - transflate-network

  task_manager:
    build:
      context: ./cmd/task_manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - transflate-network

  service3:
    build:
      context: ./cmd/task_manager
    ports:
      - "50052:50052"
    depends_on:
      - postgres
    networks:
      - transflate-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: public
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - transflate-network

volumes:
  postgres_data:

networks:
  transflate-network:
